# .yml application configuration file
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/cloud-server-eureka/
      
words: a, the

server:
  port: ${PORT:${SERVER_PORT:0}}